global using Impart.App.Domain.Models;
global using Impart.App.Services;
global using BluDay.Net.Common.CommandLine;
global using BluDay.Net.Common.Extensions.DependencyInjection;
global using BluDay.Net.Common.Models;
global using BluDay.Net.Common.Services;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Messaging;
global using System.ComponentModel.DataAnnotations;